spring:
  cloud:
    stream:
      bindings:
        input: {destination: test-topic, content-type: application/json, group: test-group}
      rocketmq:
        binder:
          namesrv-addr: 192.168.171.168:9876
  application:
    name: rockermq-consumer

server:
  port: 9094